equadratures/parameter.py
equadratures/stats.py
tests/test_stats.py

Should work at least in python 2.7

Fix to test_stats and sampling in uniform distribution

---

equadratures/plotting.py
equadratures/stats.py
ipython-notebooks/Skewness and Kurtosis.ipynb

Please find ipython-notebooks/Skewness and Kurtosis to run the final command.

Temp build to run notebook

---

equadratures/__init__.py
equadratures/basis.py
equadratures/parameter.py
equadratures/polyint.py
equadratures/polylsq.py
equadratures/polyreg.py
equadratures/stats.py
equadratures/utils.py

Incorporates changes from eq-dev.

Change polyreg

---

tests/test_dr.py

Hi Pranay,
Please check the test cases. The errors are consistently failure to process the code file, say class polyreg, and resulting in the error message as 'object is not callable' or 'unexpected keyword argument'.
Thanks a lot!
Henry

Update DR tests

---

equadratures/poly.py
tests/test_savepoly.py

Add test for poly saving capability.

---

equadratures/dr.py

Previous version forgot to update V_plus across iterations

Fix bug in VP

---

equadratures/development/induced_distributions.py

This class would feature a christoffel function
weighted induced distribution

add skeleton for the induced distribution sampling technique

---

equadratures/induced_distributions.py

This commit also includes:
review and minor changes for the qudrature sampling
and generation of the sampling function with appropriate measure

add mixture sampling of a multivariate induced distribution

---

equadratures/solver.py

Small change to how the best epsilon is chosen to make it more robust.

Small change to basis_pursuit_denoising

---

equadratures/optimisation.py
source/_documentation/tutorial_17.txt
tests/test_optimisation.py

Changed inputs to Optimisation class to use dictionaries and modified the tests and tutorial accordingly

Changes to Optimisation: accept dictionary inputs

---

equadratures/optimisation.py
equadratures/subspaces.py
tests/test_optimisation.py

Also made a little change to subspaces such that an initial subspace matrix can be supplied as an input. Tests for OMoRF take a little longer (approx 4 mins on my computer).

Added OMoRF method

---

equadratures/polytree.py

This pull request includes minor optimisations and a cardinality warning for PolyTree.

Polytree Core Implementation

---

README.md

Update links to new website in README.md

Update website links in github readme

---

equadratures/polytree.py

Initially removed for performance, has been reimplemented to run faster

Smoothing reimplemented

---

equadratures/poly.py

Signed-off-by: mHash1m <hashimchaudry23@gmail.com>

fix typo in poly sample constructor initialisations

---

equadratures/plot.py

Currently, the <code>plot_sobol_indices()</code> method provides a plot for only 1st order sobol indices, 
Added the functionality for choosing the order of the indices (1, 2, 3) . Also providing a default parameters if none provided

Added plotting function for sobol indices of higher order

---

equadratures/plot.py

Used numpy function arange instead of scipy.

Removed a bug from function plot_Sobol_indices

---

equadratures/plot.py
equadratures/solver.py

Added the function regularisation path for <code>elastic_net</code> solver. Also, a wrapper function is created in <code>solver.py</code> for calling the plotting function directly from <code>Polynomial.solver.plot_regpath()</code>

Added plotting function for regularisation path 

---

equadratures/plot.py
equadratures/poly.py
equadratures/solver.py

Added <code>elements</code> parameters in regularisation path, whose value is calculated using <code>poly.basis.elements</code>

Added labels for the regularisation path

---

equadratures/poly.py

Added the attribute "variable" to match syntax in Parameter. Also added a line into the summary output function as also discussed in above.

Added variable attribute to poly

---

equadratures/__init__.py
equadratures/logistic_poly.py
equadratures/poly.py
equadratures/sampling_methods/montecarlo.py
tests/test_logisticpoly.py

Logistic poly
